#
# Makefile for Encryption && Decryption
# Author: Prateek Jain
# 
# run make clean to clean
# run make to generate compile
COMPILER=g++ -std=c++0x
CFLAGS=-w

bbst:
	$(COMPILER) $(CLAGS) -w -o bbst RBTree.cpp Main.cpp
clean:
	rm -rf *.o bbst
